# Priority 라벨
- name: Priority: Critical
  color: B60205
  description: 우선순위 긴급

- name: Priority: High
  color: D93F0B
  description: 우선순위 상

- name: Priority: Medium
  color: FBCA04
  description: 우선순위 중

- name: Priority: Low
  color: C2E0C6
  description: 우선순위 하

# Status 라벨
- name: Status: To Do
  color: F9D0C4
  description: 처리해야 되는 이슈

- name: Status: In Progress
  color: 0E8A16
  description: 현재 처리 중인 이슈

- name: Status: Reviewing
  color: 0366D6
  description: 처리하고 리뷰 중인 이슈

- name: Status: Pending
  color: CCCCCC
  description: 보류 중인 이슈

- name: Status: Done
  color: 1D76DB
  description: 리뷰까지 완료된 이슈

- name: Status: Duplicated
  color: E4E669
  description: 이미 보고된 이슈

# Type 라벨
- name: Type: Bugfix/Function
  color: B60205
  description: 정상 동작하지 않는 기능

- name: Type: Bugfix/UI
  color: F66A0A
  description: 정상 표시되지 않는 UI

- name: Type: Feature/Function
  color: 84D4F3
  description: 새로운 기능 및 개선 사항

- name: Type: Feature/Document
  color: 0075CA
  description: 문서 추가 및 보완 작업
